### PR TITLE
Fix to PrepareEnvironment

### PR DESCRIPTION
**Pull request by tjayharvey**
Fixed the PrepareEnviroment routine in Start!/Program to actually write the opened assembly and to the correct location.

Note: Due to weirdness with initial setup of the repository and how I applied the change, it looked like I changed most of the file (I took my initial repo offline, created a new one from the fork, and copied the text of the change file). There really should only be 3-4 lines of difference at the end of PrepareEnvironment(). I'll try not to confuse things in further pulls.

### CODE REVIEW

**Comment by tjayharvey** [comment]
Apparently I only get one pull request until you process the other one? In any case, I've added the fixes to the console mod. There are three commands still disabled due to dependencies.

**Comment by GregRos** [comment]
I'm working on merging your stuff with a few unpushed commits on my side (small stuff). Also, I will put the PrepareEnvironment thing in a separate project because... rather obviously... if your environment is out of date, it won't compile, because the Start project depends on the IEMod project.

As a side note, IMO the Equals method should use reflection because the class is subject to change, and it's error prone to always write the checks explicitly.

**Comment by tjayharvey** [comment]
Yes, here that makes sense because you won't be doing the check all that often, so code fragility is more important than performance. I'll see if I can fix that this evening (though I actually want to play the game some tonight).

Speaking of performance, I was trying out fixing one of the other broken mods and found a serious drop in game performance just for patching a method with the body shown in the decompiled assembly (without applying any changes). Granted, the decompiled code is the tool's best guess, but it seems strange that there would be that much difference in the compiled version. Is there anything else I should be aware of with patch/injection process that could be affecting its performance?

**Comment by GregRos** [comment]
That usually means an exception has been thrown. I'm not sure why that would happen though. You can check if that happened in `C:\Games\Pillars of Eternity\PillarsOfEternity_Data\output_log.txt`. The injection process doesn't by itself introduce performance issues.

**Comment by GregRos** [comment]
Also, since I've merged this pull request, it has disappeared from the active list. It might be better to move the discussion to Issues. 

I also added some other changes to the code.

**Pull request merged**
